name: "user-web"
port: 8021
user_srv:
  name: 'user-srv'
jwt:
  key: 'iusd7Djsdkf21039@7873487FHJSDGfj'
sms:
  key: ""
  secret: ""
redis:
  host: "39.102.215.201"
  port: 6379
consul:
  host: "39.102.215.201"
  port: 8500